% Script generated by Brainstorm (05-Jan-2016)

%% Changes made - lines 23 - 27 - Works. Have to figure out a way to loop 
%% based on no. of raw files. Raw files input from txt?

% Input files
sFiles = [];
SubjectNames = {...
    'Subject01'};
RawFiles = {...
    'C:\Users\pseb1015\Documents\sample_resting\Data\subj002_spontaneous_20111102_01_AUX.ds',
    'C:\Users\pseb1015\Documents\sample_resting\Data\subj002_noise_20111104_02.ds'
    };

% Start a new report
bst_report('Start', sFiles);

%% while rawfiles contain subjectnames in path. NOT? skip to next sub file 
%% and next raw file

% Process: Create link to raw file
sFiles = bst_process('CallProcess', 'process_import_data_raw', sFiles, [], ...
    'subjectname', SubjectNames{1}, ...
    'datafile', {RawFiles{1}, 'CTF'},...
    'channelreplace', 0, ...
    'channelalign', 1);
sFiles = bst_process('CallProcess', 'process_import_data_raw', sFiles, [], ...
    'subjectname', SubjectNames{1}, ...
    'datafile', {RawFiles{2}, 'CTF'},...
    'channelreplace', 0, ...
    'channelalign', 1);
% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);

