% Script generated by Brainstorm (05-Jan-2016)

% Input files
sFiles = [];
SubjectNames = {...
    'Subject01'};
RawFiles = {...
    'C:\Users\pseb1015\Documents\sample_resting\Data\subj002_noise_20111104_02.ds'};

% Start a new report
bst_report('Start', sFiles);

% Process: Create link to raw file
sFiles = bst_process('CallProcess', 'process_import_data_raw', sFiles, [], ...
    'subjectname', SubjectNames{1}, ...
    'datafile', {RawFiles{1}, 'CTF'}, ...
    'channelreplace', 0, ...
    'channelalign', 1);

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);

