function[] = artifact_detection(sFiles)


% Start a new report
bst_report('Start', sFiles);

% Process: Detect heartbeats
sFiles = bst_process('CallProcess', 'process_evt_detect_ecg', sFiles, [], ...
    'channelname', 'ECG', ...
    'timewindow', [], ...
    'eventname', 'cardiac');

% Process: Detect eye blinks
sFiles = bst_process('CallProcess', 'process_evt_detect_eog', sFiles, [], ...
    'channelname', 'VEOG', ...
    'timewindow', [], ...
    'eventname', 'blink');

% Process: Remove simultaneous
sFiles = bst_process('CallProcess', 'process_evt_remove_simult', sFiles, [], ...
    'remove', 'cardiac', ...
    'target', 'blink', ...
    'dt', 0.25, ...
    'rename', 0);

% Process: Detect other artifacts
sFiles = bst_process('CallProcess', 'process_evt_detect_badsegment', sFiles, [], ...
    'timewindow', [], ...
    'sensortypes', 'MEG, EEG', ...
    'threshold', 3, ...  % 3
    'isLowFreq', 1, ...
    'isHighFreq', 1);

% Process: SSP ECG: cardiac
sFiles = bst_process('CallProcess', 'process_ssp_ecg', sFiles, [], ...
    'eventname', 'cardiac', ...
    'sensortypes', 'MEG', ...
    'usessp', 1, ...
    'select', 1);

% Process: SSP EOG: blink
sFiles = bst_process('CallProcess', 'process_ssp_eog', sFiles, [], ...
    'eventname', 'blink', ...
    'sensortypes', 'MEG', ...
    'usessp', 1, ...
    'select', 1);

% Process: Snapshot: SSP projectors
sFiles = bst_process('CallProcess', 'process_snapshot', sFiles, [], ...
    'target', 2, ...  % SSP projectors
    'modality', 1, ...  % MEG (All)
    'orient', 1, ...  % left
    'time', 0, ...
    'contact_time', [0, 0.1], ...
    'contact_nimage', 12, ...
    'threshold', 30, ...
    'Comment', '');

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);

end