function[] = import_meg(sFiles,SubjectNames)


% Start a new report
bst_report('Start', sFiles);

% Process: Import MEG/EEG: Time
sFiles = bst_process('CallProcess', 'process_import_data_time', sFiles, [], ...
    'subjectname', SubjectNames{1}, ...
    'condition', '', ...
    'timewindow', [], ...
    'split', 5, ...
    'ignoreshort', 1, ...
    'usectfcomp', 1, ...
    'usessp', 1, ...
    'freq', [], ...
    'baseline', []);

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);

end