function [] = import_anatomy(SubjectNames,RawFiles)

sFiles = [];

% Start a new report
bst_report('Start', sFiles);

% Process: Import anatomy folder
sFiles = bst_process('CallProcess', 'process_import_anatomy', sFiles, [], ...
    'subjectname', SubjectNames{1}, ...
    'mrifile', {RawFiles{1}, 'FreeSurfer'}, ...
    'nvertices', 15000, ...
    'nas', nas, ...
    'lpa', lpa, ...
    'rpa', rpa, ...
    'ac', ac, ...
    'pc', pc, ...
    'ih', ih);

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);


end

