function[]=psd_source(sFiles_t)

for i = 1:length(sFiles_t)
% Input files
    disp(sFiles_t(i));
    sFiles = sFiles_t(i);
    
% Start a new report
bst_report('Start', sFiles);

% Process: Power spectrum density (Welch)
sFiles = bst_process('CallProcess', 'process_psd', sFiles, [], ...
    'timewindow', [], ...
    'win_length', 2, ...
    'win_overlap', 50, ...
    'clusters', [], ...
    'scoutfunc', 1, ...  % Mean
    'edit', struct(...
         'Comment', 'Power', ...
         'TimeBands', [], ...
         'Freqs', [], ...
         'ClusterFuncTime', 'none', ...
         'Measure', 'power', ...
         'Output', 'all', ...
         'SaveKernel', 0));

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);

end
end