% Script generated by Brainstorm (05-Jan-2016)

NO_OF_BLOCKS = 120;

% Process each time block separately for all scouts. 
for i = 1:NO_OF_BLOCKS 
    
    % Convert block number to string 
    if (i/10 )<1
        temp = strcat('00', int2str(i));
    elseif (i/10)<10
        temp = strcat('0', int2str(i));
    else temp = int2str(i);
    end
    
    % Input files
    filename = strcat('link|Subject01/subj002_spontaneous_20111102_01_AUX/results_wMNE_MEG_KERNEL_160106_2130.mat|Subject01/subj002_spontaneous_20111102_01_AUX/data_block',temp,'.mat');
    sFiles = {...
        filename};

    % Start a new report
    bst_report('Start', sFiles);

    % Process: Power spectrum density (Welch)
    sFiles = bst_process('CallProcess', 'process_psd', sFiles, [], ...
        'timewindow', [], ...
        'win_length', 2, ...
        'win_overlap', 50, ...
        'clusters', {'Desikan-Killiany', {'bankssts L', 'bankssts R', 'caudalanteriorcingulate L', 'caudalanteriorcingulate R', 'caudalmiddlefrontal L', 'caudalmiddlefrontal R', 'cuneus L', 'cuneus R', 'entorhinal L', 'entorhinal R', 'frontalpole L', 'frontalpole R', 'fusiform L', 'fusiform R', 'inferiorparietal L', 'inferiorparietal R', 'inferiortemporal L', 'inferiortemporal R', 'insula L', 'insula R', 'isthmuscingulate L', 'isthmuscingulate R', 'lateraloccipital L', 'lateraloccipital R', 'lateralorbitofrontal L', 'lateralorbitofrontal R', 'lingual L', 'lingual R', 'medialorbitofrontal L', 'medialorbitofrontal R', 'middletemporal L', 'middletemporal R', 'paracentral L', 'paracentral R', 'parahippocampal L', 'parahippocampal R', 'parsopercularis L', 'parsopercularis R', 'parsorbitalis L', 'parsorbitalis R', 'parstriangularis L', 'parstriangularis R', 'pericalcarine L', 'pericalcarine R', 'postcentral L', 'postcentral R', 'posteriorcingulate L', 'posteriorcingulate R', 'precentral L', 'precentral R', 'precuneus L', 'precuneus R', 'rostralanteriorcingulate L', 'rostralanteriorcingulate R', 'rostralmiddlefrontal L', 'rostralmiddlefrontal R', 'superiorfrontal L', 'superiorfrontal R', 'superiorparietal L', 'superiorparietal R', 'superiortemporal L', 'superiortemporal R', 'supramarginal L', 'supramarginal R', 'temporalpole L', 'temporalpole R', 'transversetemporal L', 'transversetemporal R'}}, ...
        'scoutfunc', 1, ...  % Mean
        'edit', []);

    % Save and display report
    ReportFile = bst_report('Save', sFiles);
    bst_report('Open', ReportFile);
end
