% Script generated by Brainstorm (24-Nov-2015)

% Input files
sFiles = {...
    'Subject02/@rawsubj0002_run01/data_0raw_subj0002_run01.mat'};

% Start a new report
bst_report('Start', sFiles);

% Process: Power spectrum density (Welch)
sFiles = bst_process('CallProcess', 'process_psd', sFiles, [], ...
    'timewindow', [], ...
    'win_length', 1, ...
    'win_overlap', 50, ...
    'sensortypes', 'MEG, EEG', ...
    'edit', []);

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);

