% Script generated by Brainstorm (24-Nov-2015)

% Input files
sFiles = {...
    'Subject01/@rawsubj002_noise_20111104_02/data_0raw_subj002_noise_20111104_02.mat'};

% Start a new report
bst_report('Start', sFiles);

% Process: Compute noise covariance
sFiles = bst_process('CallProcess', 'process_noisecov', sFiles, [], ...
    'baseline', [], ...
    'target', 1, ...  % Noise covariance
    'dcoffset', 1, ...  % Block by block, to avoid effects of slow shifts in data
    'method', 1, ...  % Full noise covariance matrix
    'copycond', 1, ...
    'copysubj', 0);

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);

